extends Node
const Progress = preload("res://scripts/progression.gd")
var checks = 0
var failures: Array[String] = []
func check(ok: bool,label: String) -> void:
	checks += 1
	if ok: print("PASS ",label)
	else:
		failures.append(label)
		push_error("FAIL "+label)
func frames(n: int) -> void:
	for i in range(n): await get_tree().physics_frame
	await get_tree().process_frame
func fresh() -> RefCounted:
	var p = Progress.new()
	p.reset_roster(true)
	return p
func run(game: Node) -> void:
	var p = fresh()
	check(p.roster.size()==10 and p.level_for("YOU")==1,"Ten real player profiles start at level one")
	check(p.record("YOU","ENEMY 1",1,false,false,0,1,false)==50,"Normal kill awards 50")
	check(p.record("YOU","ENEMY 2",1,true,true,3,2,true)==100,"Headshot plus one-shot awards 100 total")
	check(p.record("YOU","ENEMY 3",1,false,true,6,3,true)==100,"Full-health one-shot awards 100")
	check(p.roster.YOU.kills==3 and p.roster["ENEMY 1"].deaths==1,"Scoreboard records kills and deaths")
	p.record("ENEMY 1","YOU",2,false,false,7,4,false)
	check(p.roster.YOU.deaths==1 and p.xp_for("ENEMY 1")==50 and p.xp_for("YOU")==250,"Bot kill records death without removing earned XP")
	p = fresh()
	for i in range(4): p.record("YOU","ENEMY 1",1,false,true,i*1.1,10+i,true)
	check(p.awards[0].total==400 and p.chain.count==4,"Four rapid sniper kills stack 400 points")
	check(p.xp_for("YOU")==400,"No premature tier bonuses")
	p.update(4.66)
	check(p.xp_for("YOU")==500 and p.awards[0].total==400,"Multi settles for 100 while base animation finishes")
	p.update(5.31)
	check(p.awards[0].bonus and p.awards[0].total==100,"Separate 100 bonus follows the 400 stack")
	p.update(5.8)
	p.update(6.5)
	check(p.xp_for("YOU")==500 and p.awards.is_empty(),"Repeated updates cannot pay twice")
	for count in range(1,6):
		var tier = fresh()
		for i in range(count): tier.record("YOU","ENEMY 1",1,false,false,i*.3,30+i,false)
		var expected = [0,0,50,75,100,100][count]
		tier.update((count-1)*.3+1.36)
		check(tier.xp_for("YOU")==count*50+expected,"%d-kill chain awards only its highest tier" % count)
		if count>1: check(tier.awards.size()==2 and tier.awards[1].total==expected,"%d-kill chain has one additional animation" % count)
	p = fresh()
	p.record("YOU","ENEMY 1",1,false,true,0,40,true)
	p.record("YOU","ENEMY 2",1,false,true,.3,40,true)
	check(p.chain.collateral and p.chain.total==200,"Collateral victims count once each")
	p.record("ENEMY 1","YOU",2,false,false,.5,41,false)
	check(p.chain.is_empty() and p.awards.size()==2 and p.awards[0].total==200,"Death preserves base and bonus presentations")
	check(p.xp_for("YOU")==250,"Death settles an earned double bonus")
	p.record("YOU","ENEMY 3",1,false,true,.6,42,true)
	check(p.chain.count==1 and p.awards.size()==3,"Post-respawn kill starts a new chain")
	p.update(2.31)
	check(p.awards[0].bonus and p.awards[0].total==50,"Earlier bonus survives a new post-respawn kill")
	p.update(3.47)
	check(not p.awards[0].bonus and p.awards[0].total==100,"New chain receives its own animation")
	p.update(4.13)
	check(p.awards.is_empty() and p.xp_for("YOU")==350,"Overlapping rewards drain with exact XP")
	p.reset_roster(false)
	check(p.xp_for("YOU")==350 and p.roster.YOU.kills==0,"Mode reset keeps XP and resets K/D")
	check(Progress.new().xp_for("YOU")==0,"Fresh progression model has no implicit disk access")
	p = fresh()
	p.record("YOU","ENEMY 1",1,false,false,0,1,false)
	p.record("YOU","ENEMY 2",1,false,false,1.35,2,false)
	check(p.chain.count==2,"Kill on chain boundary counts")
	p.record("YOU","ENEMY 3",1,false,false,2.71,3,false)
	check(p.chain.count==1,"Longer gap starts a fresh chain")
	check(Progress.level_for_xp(274)==1 and Progress.level_for_xp(275)==2,"Level-two boundary is exact")
	check(Progress.threshold(1000)==25199775,"Level 1000 requires 25,199,775 XP")
	check(Progress.level_for_xp(25199774)==999 and Progress.level_for_xp(25199775)==1000,"Max-level boundary is exact")
	p = fresh()
	p.profiles.YOU=125
	for i in range(2): p.record("YOU","ENEMY 1",1,false,false,i*.3,i,false)
	p.update(1.66)
	check(p.xp_for("YOU")==275 and p.recent_level==2,"Bonus can cause a level-up")
	p = fresh()
	p.profiles.YOU=Progress.threshold(1000)-225
	for i in range(2): p.record("YOU","ENEMY 1",1,false,true,i*.3,i,true)
	p.update(1.66)
	check(p.xp_for("YOU")==Progress.threshold(1000),"Bonus respects level cap")
	var event = InputEventKey.new()
	event.physical_keycode = KEY_TAB
	event.pressed = true
	check(event.is_action_pressed("scoreboard"),"Tab opens scoreboard")
	await frames(3)
	game.start_mode("combat")
	for bot in game.combat.bots: bot.set_physics_process(false)
	game.set_active(false)
	var target=game.combat.bots[4]
	target.position=Vector3(3,.05,-5)
	await frames(3)
	var before=game.progression.xp_for("YOU")
	game.shoot_ray(Vector3(3,1.05,0),Vector3.FORWARD,3,false)
	check(game.progression.xp_for("YOU")==before+100,"Live sniper body kill earns one-shot XP")
	await frames(2)
	target.position=Vector3(3,.05,-5)
	target.health=60
	await frames(2)
	before=game.progression.xp_for("YOU")
	game.shoot_ray(Vector3(3,1.05,0),Vector3.FORWARD,3,false)
	check(game.progression.xp_for("YOU")==before+50,"Wounded-target body finish earns 50")
	check(game.progression.roster.YOU.kills==game.kills and game.progression.roster[target.target_name].deaths==2,"Live scoreboard matches actual kills")
	var base=game.progression.awards[0].total
	game.player.take_damage(100,2,"ENEMY 1")
	await frames(2)
	check(game.player.health==100 and game.progression.awards[0].total==base,"Live immediate respawn retains animation")
	game.clock += 2.01
	game.progression.update(game.clock)
	check(game.progression.awards[0].bonus and game.progression.awards[0].total==50,"Bonus plays after actual respawn")
	before=game.progression.xp_for("YOU")
	await game.start_mode("training",2)
	check(game.progression.xp_for("YOU")==before and not game.progression.awards.is_empty(),"Changing to a new map preserves session XP and rewards")
	await frames(20)
	game.player.equip(3)
	await frames(15)
	Input.action_press("aim")
	await frames(10)
	game.player.shoot()
	await frames(18)
	check(game.player.sniper_cycle>0 and game.player.scope_age>=.12 and game.player.camera.fov==32,"Sniper stays scoped through animated bolt cycle")
	check(not game.player.viewmodel.root.visible,"Gun overlay stays hidden while scoped")
	Input.action_release("aim")
	await frames(4)
	check(game.player.viewmodel.root.visible,"Releasing aim restores gun")
	check(game.player.viewmodel.recoil_position!=0,"Firing drives the recoil spring")
	await frames(100)
	check(absf(game.player.viewmodel.recoil_position)<.001 and game.player.viewmodel.casings.is_empty(),"Recoil settles and spent casings expire")
	print("RESULT ",checks-failures.size(),"/",checks," progression checks passed")
	get_tree().quit(0 if failures.is_empty() else 1)
