extends Node
const Rig=preload("res://scripts/rig.gd")
const Collection=preload("res://scripts/cosmetics.gd")
var checks=0
var failures=[]
func check(ok: bool, title: String) -> void:
	checks+=1; print("PASS " if ok else "FAIL ",title)
	if not ok: failures.append(title)
func run(game: Node) -> void:
	await game.start_mode("training")
	var p=game.player
	p.set_process(false); p.set_physics_process(false)
	var young=Rig.build(game,Color("30bac6"),0)
	var old=Rig.build(game,Color("ed6c46"),0)
	Rig.animate(young,5,0,0,0,0,true); Rig.animate(old,5,1000,0,0,0,true)
	for frame in range(1,121):
		var speed=5.0 if frame<60 else 2.0
		Rig.animate(young,speed,frame/120.0,0,0,0,true)
		Rig.animate(old,speed,1000+frame/120.0,0,0,0,true)
	check(absf(young.legs[0].rotation.x-old.legs[0].rotation.x)<.0001,"Walking animation is independent of total match age")
	var phase=float(old.animation.phase)
	var leg=float(old.legs[0].rotation.x)
	Rig.animate(old,5.2,1001+1.0/120,0,1,0,true)
	check(absf(angle_difference(phase,old.animation.phase))<.11,"Acceleration advances stride continuously instead of jumping its phase")
	check(absf(old.legs[0].rotation.x-leg)<.08,"Speed changes keep the leg pose continuous")
	check(old.animation.reload>0 and old.animation.reload<1,"Third-person reload blends into its pose")
	Rig.animate(old,0,0,0,0,0,true)
	check(old.animation.phase==0,"Rewinding a replay resets animation integration safely")
	p.reset_at(Vector3(0,10,0))
	p.update_zoom(.016,32)
	var zoom_start=p.camera.fov
	check(zoom_start<86 and zoom_start>80,"Zoom starts with an eased movement rather than full-speed jerk")
	p.update_zoom(.104,32)
	check(is_equal_approx(p.camera.fov,32),"Sniper zoom still reaches its exact FOV within 120 ms")
	p.update_zoom(.03,86); var mid=p.camera.fov; p.update_zoom(0,32)
	check(is_equal_approx(p.camera.fov,mid),"Reversing aim preserves the current FOV without a snap")
	p.reset_at(Vector3(0,10,0)); p.weapon=0; p.viewmodel.update_pose(0)
	p.equip(1); p.viewmodel.update_pose(1.0/120)
	check(p.weapon==1 and p.viewmodel.shown_weapon==0,"Logical weapon changes immediately while the old visual lowers")
	check(p.viewmodel.swap_lower>0 and p.viewmodel.swap_lower<1,"Weapon transition starts gradually")
	for i in range(8): p.viewmodel.update_pose(1.0/120)
	check(p.viewmodel.shown_weapon==1,"New weapon appears after the holster beat")
	for i in range(24): p.viewmodel.update_pose(1.0/120)
	check(p.viewmodel.swap_lower==0 and p.viewmodel.models[1].visible,"Weapon draw settles without a lingering offset")
	p.equip(3); p.viewmodel.update_pose(.015); p.equip(0)
	for i in range(30): p.viewmodel.update_pose(.01)
	check(p.viewmodel.shown_weapon==0 and p.viewmodel.swap_lower==0,"Rapid weapon cycling settles to the last requested weapon")
	p.reset_at(Vector3(0,10,0)); p.equip_grenade("blast"); p.short_toss_requested=true
	var before=game.grenades.size()
	p._physics_process(.016)
	check(p.toss_buffer>0 and p.blast_count==1,"Early grenade click queues during equip without consuming ammunition")
	for i in range(13): p._physics_process(.016)
	check(p.blast_count==0 and game.grenades.size()==before+1,"Queued toss fires exactly once when equipment is ready")
	for i in range(20): p._physics_process(.016)
	check(game.grenades.size()==before+1,"A consumed grenade buffer never repeats")
	p.refill(); p.equip_grenade("blast"); p.short_toss_requested=true; p._physics_process(.01)
	game.set_active(false); game.set_active(true)
	check(p.toss_buffer==0,"Opening the menu cancels pending throws")
	p.reset_at(Vector3.ZERO)
	Collection.paint(young.root,"armor_royal",true)
	game.effects.fall(young.root)
	check(not game.effects.bodies.is_empty(),"Cosmetic-equipped defeated characters create a fading body")
	var shaders=game.effects.bodies[-1].materials.filter(func(mat): return mat is ShaderMaterial)
	check(not shaders.is_empty(),"Body fading preserves cosmetic shaders instead of casting them to standard materials")
	game.effects._process(.6)
	if DisplayServer.get_name()!="headless": await RenderingServer.frame_post_draw
	check(shaders.all(func(mat): return float(mat.get_shader_parameter("corpse_alpha"))<1),"Cosmetic body shaders fade on render frames")
	check(not Collection.finish("armor_royal").shader.code.contains("corpse_alpha"),"Death effects never mutate a shared inventory material")
	game.effects._process(.3)
	check(game.effects.bodies.is_empty(),"Expired bodies are released")
	young.root.queue_free(); old.root.queue_free()
	await game.start_mode("combat")
	for actor in game.combat.actors(): actor.set_physics_process(false)
	var bot=game.combat.bots[0]; bot.set_process(false)
	bot.presentation.reset(bot.global_transform)
	var start=bot.global_position
	bot.presentation.begin_tick(bot.global_transform); bot.position.x+=.12; bot.presentation.end_tick(bot.global_transform)
	bot.presentation.apply(bot.rig.root,bot,.5)
	check(is_equal_approx(bot.rig.root.global_position.x,start.x+.06),"Bot visuals interpolate between simulation positions")
	check(is_equal_approx(bot.position.x,start.x+.12),"Bot interpolation leaves the authoritative body untouched")
	check(bot.weapon_node.get_parent()==bot.rig.root,"Bot weapon follows the same interpolated pose as its hands")
	bot.reset()
	check(bot.presentation.previous==bot.presentation.current,"Bot respawn clears old interpolation history")
	var remote=game.Player.new(); remote.game=game; remote.locally_controlled=false
	game.add_child(remote); remote.set_physics_process(false)
	remote.viewmodel.root.show(); remote.viewmodel.title.show(); remote.health=0
	remote._process(.016)
	check(not remote.viewmodel.root.visible and not remote.viewmodel.title.visible,"Dead host-side humans leave neither a model nor a floating teammate tag")
	remote.queue_free()
	game.prefs.data.quality=1; game.apply_settings()
	check(game.get_viewport().msaa_3d==Viewport.MSAA_2X and game.get_viewport().screen_space_aa==Viewport.SCREEN_SPACE_AA_DISABLED,"Balanced quality uses anti-aliasing supported by Compatibility")
	var prefs=game.Preferences.new("user://feel_settings_test.json")
	prefs.data.render_scale=.75; prefs.save()
	var restored=game.Preferences.new(prefs.path); restored.load_profile()
	check(is_equal_approx(restored.data.render_scale,.75),"Render scale persists independently of resolution and HUD size")
	DirAccess.remove_absolute(prefs.path); DirAccess.remove_absolute(prefs.path+".bak")
	print("FEEL_RESULT ",checks-failures.size(),"/",checks)
	shaders.clear(); young.clear(); old.clear()
	await get_tree().process_frame
	await get_tree().process_frame
	get_tree().quit(0 if failures.is_empty() else 1)
